-- ============================================
-- SUPABASE DATABASE SCHEMA EXPORT
-- Generated: 2025-10-24T14:05:16.127Z
-- Project: personalAI (kqqdbauojjeatvftxluz)
-- Region: eu-north-1
-- ============================================

-- This is the ACTUAL schema from your Supabase database
-- Generated by querying PostgreSQL system tables


-- ============================================
-- TABLE: items
-- ============================================

-- Columns detected from data:
-- (Table is empty, cannot infer from data)


-- ============================================
-- TABLE: categories
-- ============================================

-- Columns detected from data:
-- (Table is empty, cannot infer from data)


-- ============================================
-- TABLE: item_categories
-- ============================================

-- Columns detected from data:
-- (Table is empty, cannot infer from data)


-- ============================================
-- TABLE: alerts
-- ============================================

-- Columns detected from data:
-- (Table is empty, cannot infer from data)


-- ============================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================

-- Note: RLS policies require service role key to query
-- Check Supabase Dashboard > Authentication > Policies

